spring:
  application:
    name: GoCardless open banking service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
logging:
  level:
    org.springframework.security: debug
    org.hibernate.sql: debug
#    com.example.gocardlessopenbanking: debug

app:
  gocardless:
    api-url: ${GOCARDLESS_API_URL:https://bankaccountdata.gocardless.com}
    secret-id: ${GOCARDLESS_SECRET_ID}
    secret-key: ${GOCARDLESS_SECRET_KEY}
    redirect-url: ${GOCARDLESS_REDIRECT_URL:http://localhost:8080/redirect}
